# Generated by Django 5.0 on 2025-09-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowers',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
