# Generated by Django 5.0 on 2025-09-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_flowers_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowers',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
