# Generated by Django 5.0 on 2025-09-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowers',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='images'),
        ),
    ]
